### ISSUE TITLE
Primer design for UEA project

### ISSUE THREAD

**Issue by manulera** [manulera/OpenCloning_backend#254]
cc @gyanezfeliu

## Requirements

The requirements mentioned by Amanda for the primer design were:

* Tm: Optimal 60-62°C, but this can be extended to 58-64°C if necessary, though all primers ideally need to be within 5°C to ensure they can be run on the same plate for high-throughput.

    * This is calculated for 50mM Na+ and 1.5mM Mg++

    * Primers within the same pair/flanking set need to be within 5°C.

* Primer size: 17-30nt.

* GC content: between 35 and 65%

* A 1 or 2nt GC clamp at the 3’ end of the primer can help to anchor and achieve higher PCR efficiencies, though this is optional.

* In the last 5nt of the primer I typically look for a good mix of G/C and A/T to ensure a good clamp (40-60% GC content). I’m not sure how easy it would be to check this, but I thought it was worth adding in just in case.

* Product size: We are aiming for ~950bp homologous arms, though this can be shortened considerably if necessary to find good primers/ remove BsaI sites.

* I avoid primers with long repetitions of nucleotides in a row (e.g. TTTTT)

* I also check for heterodimers, self dimers and hairpin loops.

    * Self-dimers – try to avoid anything with a ΔG below -10

    * Heterodimers – try to avoid ΔG below -10

    * Hairpin loops - avoid ΔG below -5

    * There is some flexibility here, especially if location is more essential or if there are limited places to design the primers.

* I avoid primers with homology to other sites in the genome.

## What to use

@gyanezfeliu suggested to use the [primer3-py](https://libnano.github.io/primer3-py) library for this. Will have to look into the settings to see if all those conditions can be met

**Comment by manulera** [comment]
cc @AmandaHopes

**Comment by manulera** [comment]
Using primer3, there seems to be options so set all those preferences, just a few will need some input. I have labeled them in the minimal example below with `< Needs input`

## Primer concentration

It is possible to set primer concentration as a parameter, maybe we want to add that as well? Not sure what it's used for, I guess for heterodimers and so.

## Thermodynamic calculation units

For self-dimers, heterodimers, etc., primer3 has parameters where you can set thresholds, but the units are either a scoring or temperature. I guess it's possible to express those deltaG thresholds as temperatures? Not a huge thermodynamic nerd here!

I have put 40 for now, which might be a bit low since the default is 47, but anyway let me know what you think is best!

![Screenshot 2024-12-20 at 11 54 08](https://github.com/user-attachments/assets/2bdd1811-8ac1-475d-9300-8f6f6c9a1295)

## Minimal example

Below a python example that finds some primers. The text of the requirements is written as comments along with the corresponding parameters

```python
from primer3 import bindings
import json

amanda_settings = {
    # Tm: Optimal 60-62°C, but this can be extended to 58-64°C if necessary.
    # All primers need to ideally be within 5°C to ensure they can be run on the same plate for high-throughput.
    "PRIMER_OPT_TM": 61,  # Optimal Tm
    "PRIMER_MIN_TM": 58,  # Minimum Tm
    "PRIMER_MAX_TM": 64,  # Maximum Tm
    "PRIMER_PAIR_MAX_DIFF_TM": 5,  # Maximum Tm difference within a pair
    # Salt concentration: 50mM NaCl, 1.5mM MgCl2
    "PRIMER_SALT_MONOVALENT": 50.0,
    "PRIMER_SALT_DIVALENT": 1.5,
    # nM primer concentration < Needs input
    "PRIMER_DNA_CONC": 50.0,
    # Primer size: 17-30nt.
    "PRIMER_MIN_SIZE": 17,  # Minimum primer length
    "PRIMER_MAX_SIZE": 30,  # Maximum primer length
    "PRIMER_OPT_SIZE": 22,  # Typical optimal size (can be adjusted)
    # GC content: between 35 and 65%.
    "PRIMER_MIN_GC": 35,  # Minimum GC content percentage
    "PRIMER_MAX_GC": 65,  # Maximum GC content percentage
    # A 1 or 2nt GC clamp at the 3’ end of the primer helps with PCR efficiency.
    "PRIMER_GC_CLAMP": 2,  # Number of GC bases required at the 3’ end
    # Product size: ~950bp homologous arms, though this can be shortened if necessary.
    "PRIMER_PRODUCT_SIZE_RANGE": [[800, 1000]],  # Product size range in base pairs
    # Avoid primers with long repetitions of nucleotides in a row (e.g., TTTTT).
    "PRIMER_MAX_POLY_X": 4,  # Maximum allowable repetitions of a single nucleotide
    # Dimer and hairpin structure considerations:
    # Self-dimers – avoid ΔG below -10
    # Heterodimers – avoid ΔG below -10
    # Hairpin loops - avoid ΔG below -5
    "PRIMER_MAX_SELF_ANY": 40,  # < Needs input
    "PRIMER_MAX_SELF_END": 40,  # < Needs input
    "PRIMER_MAX_HAIRPIN": 40,  # < Needs input
}

# Avoid primers with homology to other sites in the genome.
# This can be checked using external tools like BLAST for specificity.


seq = 'ATGCAAACAGTAATGATGGATGACATTCAAAGCACTGATTCTATTGCTGAAAAAGATAATCACTCTAATAATGAATCTAACTTTACTTGGAAAGCGTTTCGTGAACAAGTGGAAAAGCATTTTTCTAAAATTGAAAGGCTTCACCAAGTCCTTGGAACAGATGGAGACAATTCATCATTATTTGAGTTGTTTACAACGGCAATGAATGCCCAGCTTCATGAAATGGAACAGTGCCAGAAAAAACTTGAAGATGACTGTCAGCAAAGAATTGATTCAATCAGATTTTTGGTTTCCTCATTAAAGTTAACGGATGATACTTCTAGTCTCAAAATTGAGTCTCCTTTAATTCAGTGTTTGAATCGTTTGTCAATGGTAGAAGGACAATATATGGCACAGTATGATCAAAAGTTAAGTACGATTAAAGAAATGTATCACAAATTGGAGTCATATTGTAACCGCTTAGGAAGTCCGTTCGTTTTACCTGATTTTGAGAATTCATTTTTATCTGATGTATCCGATGCTTTTACTGAATCTTTGAGAGGACGCATCAACGAAGCCGAAAAGGAGATTGATGCGAGATTAGAGGTTATTAATTCCTTTGAAGAAGAAATTTTGGGTTTGTGGTCTGAACTCGGTGTTGAGCCCGCTGATGTTCCACAATACGAACAATTGCTTGAATCCCATACTAATCGACCAAATGATGTTTATGTTACTCAAGAACTTATCGACCAACTTTGCAAGCAAAAAGAAGTTTTTTCCGCTGAAAAAGAAAAGAGAAGTGATCATTTAAAAAGTATACAATCAGAAGTTAGCAACTTGTGGAATAAGCTTCAAGTTTCTCCCAATGAACAAAGTCAATTTGGCGATTCATCAAACATTAATCAAGAAAATATTTCATTATGGGAAACTGAACTTGAAAAACTTCATCAGTTAAAAAAGGAGCATTTACCCATTTTTTTAGAAGACTGTCGTCAACAAATTCTTCAGCTTTGGGATTCTCTGTTTTATTCAGAAGAACAAAGAAAGTCCTTTACACCTATGTATGAAGACATTATTACAGA'

out = bindings.design_primers(
    seq_args={
        'SEQUENCE_ID': 'MH1000',
        'SEQUENCE_TEMPLATE': seq,
        'SEQUENCE_INCLUDED_REGION': [0, 1000],
    },
    global_args=amanda_settings,
)


print(json.dumps(out, indent=4))

```

The output is quite extensive, and looks like below. I guess we could include this in the output of the pipeline, in case people want to revise the primer properties in more detail.

```json
{
    "PRIMER_LEFT_EXPLAIN": "considered 1463, GC content failed 1137, GC clamp failed 123, low tm 82, high tm 42, high hairpin stability 9, ok 70",
    "PRIMER_RIGHT_EXPLAIN": "considered 1423, GC content failed 1207, GC clamp failed 119, low tm 47, high tm 4, long poly-x seq 6, ok 40",
    "PRIMER_PAIR_EXPLAIN": "considered 207, unacceptable product size 201, ok 6",
    "PRIMER_LEFT_NUM_RETURNED": 5,
    "PRIMER_RIGHT_NUM_RETURNED": 5,
    "PRIMER_INTERNAL_NUM_RETURNED": 0,
    "PRIMER_PAIR_NUM_RETURNED": 5,
    "PRIMER_PAIR": [
        {
            "PENALTY": 3.9648842188285016,
            "COMPL_ANY_TH": 4.370223297027906,
            "COMPL_END_TH": 4.370223297027906,
            "PRODUCT_SIZE": 903,
            "PRODUCT_TM": 82.23354518821891
        },
        {
            "PENALTY": 4.0423971231354585,
            "COMPL_ANY_TH": 4.370223297027906,
            "COMPL_END_TH": 4.370223297027906,
            "PRODUCT_SIZE": 904,
            "PRODUCT_TM": 82.2636623493044
        },
        {
            "PENALTY": 4.765574690927394,
            "COMPL_ANY_TH": 4.370223297027906,
            "COMPL_END_TH": 4.370223297027906,
            "PRODUCT_SIZE": 904,
            "PRODUCT_TM": 82.2636623493044
        },
        {
            "PENALTY": 4.843087595234351,
            "COMPL_ANY_TH": 4.370223297027906,
            "COMPL_END_TH": 4.370223297027906,
            "PRODUCT_SIZE": 905,
            "PRODUCT_TM": 82.29371295312778
        },
        {
            "PENALTY": 5.335561884391552,
            "COMPL_ANY_TH": 0.0,
            "COMPL_END_TH": 0.0,
            "PRODUCT_SIZE": 864,
            "PRODUCT_TM": 82.23839399466657
        }
    ],
    "PRIMER_LEFT": [
        {
            "PENALTY": 0.5228108490858858,
            "SEQUENCE": "AAAGCGTTTCGTGAACAAGTGG",
            "COORDS": [
                90,
                22
            ],
            "TM": 60.477189150914114,
            "GC_PERCENT": 45.45454545454545,
            "SELF_ANY_TH": 5.54406997404061,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 38.17683561045931,
            "END_STABILITY": 4.0
        },
        {
            "PENALTY": 0.5228108490858858,
            "SEQUENCE": "AAAGCGTTTCGTGAACAAGTGG",
            "COORDS": [
                90,
                22
            ],
            "TM": 60.477189150914114,
            "GC_PERCENT": 45.45454545454545,
            "SELF_ANY_TH": 5.54406997404061,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 38.17683561045931,
            "END_STABILITY": 4.0
        },
        {
            "PENALTY": 1.3235013211847786,
            "SEQUENCE": "GAAAGCGTTTCGTGAACAAGTGG",
            "COORDS": [
                89,
                23
            ],
            "TM": 61.32350132118478,
            "GC_PERCENT": 47.82608695652174,
            "SELF_ANY_TH": 5.54406997404061,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 38.17683561045931,
            "END_STABILITY": 4.0
        },
        {
            "PENALTY": 1.3235013211847786,
            "SEQUENCE": "GAAAGCGTTTCGTGAACAAGTGG",
            "COORDS": [
                89,
                23
            ],
            "TM": 61.32350132118478,
            "GC_PERCENT": 47.82608695652174,
            "SELF_ANY_TH": 5.54406997404061,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 38.17683561045931,
            "END_STABILITY": 4.0
        },
        {
            "PENALTY": 1.8934885146489364,
            "SEQUENCE": "ATTGAAAGGCTTCACCAAGTCC",
            "COORDS": [
                129,
                22
            ],
            "TM": 59.106511485351064,
            "GC_PERCENT": 45.45454545454545,
            "SELF_ANY_TH": 0.0,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 41.335372670103595,
            "END_STABILITY": 3.85
        }
    ],
    "PRIMER_RIGHT": [
        {
            "PENALTY": 3.442073369742616,
            "SEQUENCE": "CCAAAGCTGAAGAATTTGTTGACG",
            "COORDS": [
                992,
                24
            ],
            "TM": 59.557926630257384,
            "GC_PERCENT": 41.666666666666664,
            "SELF_ANY_TH": 0.0,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 33.12879722868007,
            "END_STABILITY": 4.35
        },
        {
            "PENALTY": 3.5195862740495727,
            "SEQUENCE": "CCCAAAGCTGAAGAATTTGTTGACG",
            "COORDS": [
                993,
                25
            ],
            "TM": 61.51958627404957,
            "GC_PERCENT": 44.0,
            "SELF_ANY_TH": 0.0,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 33.12879722868007,
            "END_STABILITY": 4.35
        },
        {
            "PENALTY": 3.442073369742616,
            "SEQUENCE": "CCAAAGCTGAAGAATTTGTTGACG",
            "COORDS": [
                992,
                24
            ],
            "TM": 59.557926630257384,
            "GC_PERCENT": 41.666666666666664,
            "SELF_ANY_TH": 0.0,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 33.12879722868007,
            "END_STABILITY": 4.35
        },
        {
            "PENALTY": 3.5195862740495727,
            "SEQUENCE": "CCCAAAGCTGAAGAATTTGTTGACG",
            "COORDS": [
                993,
                25
            ],
            "TM": 61.51958627404957,
            "GC_PERCENT": 44.0,
            "SELF_ANY_TH": 0.0,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 33.12879722868007,
            "END_STABILITY": 4.35
        },
        {
            "PENALTY": 3.442073369742616,
            "SEQUENCE": "CCAAAGCTGAAGAATTTGTTGACG",
            "COORDS": [
                992,
                24
            ],
            "TM": 59.557926630257384,
            "GC_PERCENT": 41.666666666666664,
            "SELF_ANY_TH": 0.0,
            "SELF_END_TH": 0.0,
            "HAIRPIN_TH": 33.12879722868007,
            "END_STABILITY": 4.35
        }
    ],
    "PRIMER_INTERNAL": [],
    "PRIMER_PAIR_0_PENALTY": 3.9648842188285016,
    "PRIMER_LEFT_0_PENALTY": 0.5228108490858858,
    "PRIMER_RIGHT_0_PENALTY": 3.442073369742616,
    "PRIMER_LEFT_0_SEQUENCE": "AAAGCGTTTCGTGAACAAGTGG",
    "PRIMER_RIGHT_0_SEQUENCE": "CCAAAGCTGAAGAATTTGTTGACG",
    "PRIMER_LEFT_0": [
        90,
        22
    ],
    "PRIMER_RIGHT_0": [
        992,
        24
    ],
    "PRIMER_LEFT_0_TM": 60.477189150914114,
    "PRIMER_RIGHT_0_TM": 59.557926630257384,
    "PRIMER_LEFT_0_GC_PERCENT": 45.45454545454545,
    "PRIMER_RIGHT_0_GC_PERCENT": 41.666666666666664,
    "PRIMER_LEFT_0_SELF_ANY_TH": 5.54406997404061,
    "PRIMER_RIGHT_0_SELF_ANY_TH": 0.0,
    "PRIMER_LEFT_0_SELF_END_TH": 0.0,
    "PRIMER_RIGHT_0_SELF_END_TH": 0.0,
    "PRIMER_LEFT_0_HAIRPIN_TH": 38.17683561045931,
    "PRIMER_RIGHT_0_HAIRPIN_TH": 33.12879722868007,
    "PRIMER_LEFT_0_END_STABILITY": 4.0,
    "PRIMER_RIGHT_0_END_STABILITY": 4.35,
    "PRIMER_PAIR_0_COMPL_ANY_TH": 4.370223297027906,
    "PRIMER_PAIR_0_COMPL_END_TH": 4.370223297027906,
    "PRIMER_PAIR_0_PRODUCT_SIZE": 903,
    "PRIMER_PAIR_0_PRODUCT_TM": 82.23354518821891,
    "PRIMER_PAIR_1_PENALTY": 4.0423971231354585,
    "PRIMER_LEFT_1_PENALTY": 0.5228108490858858,
    "PRIMER_RIGHT_1_PENALTY": 3.5195862740495727,
    "PRIMER_LEFT_1_SEQUENCE": "AAAGCGTTTCGTGAACAAGTGG",
    "PRIMER_RIGHT_1_SEQUENCE": "CCCAAAGCTGAAGAATTTGTTGACG",
    "PRIMER_LEFT_1": [
        90,
        22
    ],
    "PRIMER_RIGHT_1": [
        993,
        25
    ],
    "PRIMER_LEFT_1_TM": 60.477189150914114,
    "PRIMER_RIGHT_1_TM": 61.51958627404957,
    "PRIMER_LEFT_1_GC_PERCENT": 45.45454545454545,
    "PRIMER_RIGHT_1_GC_PERCENT": 44.0,
    "PRIMER_LEFT_1_SELF_ANY_TH": 5.54406997404061,
    "PRIMER_RIGHT_1_SELF_ANY_TH": 0.0,
    "PRIMER_LEFT_1_SELF_END_TH": 0.0,
    "PRIMER_RIGHT_1_SELF_END_TH": 0.0,
    "PRIMER_LEFT_1_HAIRPIN_TH": 38.17683561045931,
    "PRIMER_RIGHT_1_HAIRPIN_TH": 33.12879722868007,
    "PRIMER_LEFT_1_END_STABILITY": 4.0,
    "PRIMER_RIGHT_1_END_STABILITY": 4.35,
    "PRIMER_PAIR_1_COMPL_ANY_TH": 4.370223297027906,
    "PRIMER_PAIR_1_COMPL_END_TH": 4.370223297027906,
    "PRIMER_PAIR_1_PRODUCT_SIZE": 904,
    "PRIMER_PAIR_1_PRODUCT_TM": 82.2636623493044,
    "PRIMER_PAIR_2_PENALTY": 4.765574690927394,
    "PRIMER_LEFT_2_PENALTY": 1.3235013211847786,
    "PRIMER_RIGHT_2_PENALTY": 3.442073369742616,
    "PRIMER_LEFT_2_SEQUENCE": "GAAAGCGTTTCGTGAACAAGTGG",
    "PRIMER_RIGHT_2_SEQUENCE": "CCAAAGCTGAAGAATTTGTTGACG",
    "PRIMER_LEFT_2": [
        89,
        23
    ],
    "PRIMER_RIGHT_2": [
        992,
        24
    ],
    "PRIMER_LEFT_2_TM": 61.32350132118478,
    "PRIMER_RIGHT_2_TM": 59.557926630257384,
    "PRIMER_LEFT_2_GC_PERCENT": 47.82608695652174,
    "PRIMER_RIGHT_2_GC_PERCENT": 41.666666666666664,
    "PRIMER_LEFT_2_SELF_ANY_TH": 5.54406997404061,
    "PRIMER_RIGHT_2_SELF_ANY_TH": 0.0,
    "PRIMER_LEFT_2_SELF_END_TH": 0.0,
    "PRIMER_RIGHT_2_SELF_END_TH": 0.0,
    "PRIMER_LEFT_2_HAIRPIN_TH": 38.17683561045931,
    "PRIMER_RIGHT_2_HAIRPIN_TH": 33.12879722868007,
    "PRIMER_LEFT_2_END_STABILITY": 4.0,
    "PRIMER_RIGHT_2_END_STABILITY": 4.35,
    "PRIMER_PAIR_2_COMPL_ANY_TH": 4.370223297027906,
    "PRIMER_PAIR_2_COMPL_END_TH": 4.370223297027906,
    "PRIMER_PAIR_2_PRODUCT_SIZE": 904,
    "PRIMER_PAIR_2_PRODUCT_TM": 82.2636623493044,
    "PRIMER_PAIR_3_PENALTY": 4.843087595234351,
    "PRIMER_LEFT_3_PENALTY": 1.3235013211847786,
    "PRIMER_RIGHT_3_PENALTY": 3.5195862740495727,
    "PRIMER_LEFT_3_SEQUENCE": "GAAAGCGTTTCGTGAACAAGTGG",
    "PRIMER_RIGHT_3_SEQUENCE": "CCCAAAGCTGAAGAATTTGTTGACG",
    "PRIMER_LEFT_3": [
        89,
        23
    ],
    "PRIMER_RIGHT_3": [
        993,
        25
    ],
    "PRIMER_LEFT_3_TM": 61.32350132118478,
    "PRIMER_RIGHT_3_TM": 61.51958627404957,
    "PRIMER_LEFT_3_GC_PERCENT": 47.82608695652174,
    "PRIMER_RIGHT_3_GC_PERCENT": 44.0,
    "PRIMER_LEFT_3_SELF_ANY_TH": 5.54406997404061,
    "PRIMER_RIGHT_3_SELF_ANY_TH": 0.0,
    "PRIMER_LEFT_3_SELF_END_TH": 0.0,
    "PRIMER_RIGHT_3_SELF_END_TH": 0.0,
    "PRIMER_LEFT_3_HAIRPIN_TH": 38.17683561045931,
    "PRIMER_RIGHT_3_HAIRPIN_TH": 33.12879722868007,
    "PRIMER_LEFT_3_END_STABILITY": 4.0,
    "PRIMER_RIGHT_3_END_STABILITY": 4.35,
    "PRIMER_PAIR_3_COMPL_ANY_TH": 4.370223297027906,
    "PRIMER_PAIR_3_COMPL_END_TH": 4.370223297027906,
    "PRIMER_PAIR_3_PRODUCT_SIZE": 905,
    "PRIMER_PAIR_3_PRODUCT_TM": 82.29371295312778,
    "PRIMER_PAIR_4_PENALTY": 5.335561884391552,
    "PRIMER_LEFT_4_PENALTY": 1.8934885146489364,
    "PRIMER_RIGHT_4_PENALTY": 3.442073369742616,
    "PRIMER_LEFT_4_SEQUENCE": "ATTGAAAGGCTTCACCAAGTCC",
    "PRIMER_RIGHT_4_SEQUENCE": "CCAAAGCTGAAGAATTTGTTGACG",
    "PRIMER_LEFT_4": [
        129,
        22
    ],
    "PRIMER_RIGHT_4": [
        992,
        24
    ],
    "PRIMER_LEFT_4_TM": 59.106511485351064,
    "PRIMER_RIGHT_4_TM": 59.557926630257384,
    "PRIMER_LEFT_4_GC_PERCENT": 45.45454545454545,
    "PRIMER_RIGHT_4_GC_PERCENT": 41.666666666666664,
    "PRIMER_LEFT_4_SELF_ANY_TH": 0.0,
    "PRIMER_RIGHT_4_SELF_ANY_TH": 0.0,
    "PRIMER_LEFT_4_SELF_END_TH": 0.0,
    "PRIMER_RIGHT_4_SELF_END_TH": 0.0,
    "PRIMER_LEFT_4_HAIRPIN_TH": 41.335372670103595,
    "PRIMER_RIGHT_4_HAIRPIN_TH": 33.12879722868007,
    "PRIMER_LEFT_4_END_STABILITY": 3.85,
    "PRIMER_RIGHT_4_END_STABILITY": 4.35,
    "PRIMER_PAIR_4_COMPL_ANY_TH": 0.0,
    "PRIMER_PAIR_4_COMPL_END_TH": 0.0,
    "PRIMER_PAIR_4_PRODUCT_SIZE": 864,
    "PRIMER_PAIR_4_PRODUCT_TM": 82.23839399466657
}

```

**Comment by manulera** [comment]
Hello both,

I made a first version today, it will need some extra steps, but it roughly does what it should.

## Inputs

* Two genome regions (left and right) defined from their coordinates, from which the homology arms will be amplified.
* Primer design settings.
* A set of adapter sequences that will be used for golden gate assembly (added at the 5' end of primers designed to amplify the homology arms). I have used those from the example:
  - `adapter_left_fwd`: `ataGGTCTCtGGAG`
  - `adapter_left_rvs`: `ataGGTCTCtCATT`
  - `adapter_right_fwd`: `ataGGTCTCtGCTT`
  - `adapter_right_rvs`: `ataGGTCTCtAGCG`
* Two pre-made files that are loaded from disk:
  - `barcode.gb`: Contains a barcode sequence to be inserted
  - `common_plasmid.gb`: Contains the backbone plasmid for the assembly

## What it does

1. **Primer Design**:
   - Fetches the genomic sequences for both homology arms
   - Uses Primer3 with predefined settings to design primers for both regions
   - Adds the golden gate adapter sequences to the designed primers

2. **PCR Amplification**:
   - Simulates PCR reactions to generate the left and right homology arms with the adapter sequences

3. **Assembly Steps**:
   - Performs a Golden Gate assembly combining:
     * Left homology arm
     * Right homology arm
     * Barcode sequence
     * Common plasmid backbone
   - Simulates homologous recombination between the assembled construct and the target genomic region

## Output

* Produces a [cloning_strategy.json](https://github.com/user-attachments/files/18211901/cloning_strategy.json) (click to download) file that contains:
  - All intermediate sequences (homology arms, PCR products, etc.)
  - The final engineered allele
  - All primers with their sequences
  - The complete history of operations (sources)
  - Can be loaded into ShareYourCloning for visualization and further usage

## TODO

* [ ] Decide what the user input should be to define the location of the homology arms (coordinates, gene names, etc.)
* [ ] Further checking:
  * There should be exactly only two BsaI sites in each golden gate assembly input.
  * Primers should not bind elsewhere in the genome.
* [ ] Agree on primer design settings
* [ ] Decide what the output should include, some ideas:
  * gb files for the final product
  * a table with the primers and their properties
  * the report from primer3

**Comment by manulera** [comment]
## Feedback

From @AmandaHopes

<img width="616" alt="Image" src="https://github.com/user-attachments/assets/8e377116-d7ca-4a59-a6ea-f8b6fd92ecec" />

* With pseudogenes and gene knockouts, we can potentially place the primers either slightly up or downstream of the gene junction
* with the neutral sites we ideally don’t want to knockout anything outside of the neutral sites, primers will need to stay within the region, or bind just at the edge
* Settings for next test:
  * Left flank reverse – within 20bp upstream of the gene/neutral site to 50bp into the gene.
  * Left flank forward – roughly 950bp upstream of the reverse primer (set the flank region as 900bp upstream of the gene/neutral site junction)
  * Right flank forward – within the last 50bp of gene/neutral site to 20bp downstream of the junction
  * Right flank reverse – roughly 950bp downstream of the forward primer

* [ ] Primer concentration 500nM
* [ ] Tm 47°C
* [ ] Change the GC clamp to 1
* [ ] Would be good to see where both sets of primers sit in relation to the target gene/ sequence
* [ ] final engineered allele - keep the one that uses both homology arms and replaces the region, rather than plasmid insertion.

**Comment by manulera** [comment]
Hi @AmandaHopes, I think I have a working version with those requirements, let me know what you think. 

## General settings

> Primer concentration 500nM
> Tm 47°C
> Change the GC clamp to 1

I have changed those primer3 settings, see the difference between before and after:

<img width="719" alt="Image" src="https://github.com/user-attachments/assets/e0099e9c-aa2e-4e39-a093-a7fc57324ccf" />

## Choosing the right product

> final engineered allele - keep the one that uses both homology arms and replaces the region, rather than plasmid insertion.

Before, I was selecting any possible integration event (including whole plasmid integration events using one single homology arm). I have made it so that it only selects integration events using both homology arms, and that gives the correct result.

You can download the cloning strategy [cloning_strategy.json](https://github.com/user-attachments/files/18622583/cloning_strategy.json) and load it into ShareYourCloning.

# Displaying the primers

> Would be good to see where both sets of primers sit in relation to the target gene/ sequence

You can see those in the locus now, see the image below in the tree view.

<img width="301" alt="Image" src="https://github.com/user-attachments/assets/8b178939-7200-49e4-8bcf-0c2a28511324" />

If you click on the eye to see the full sequence, you can see the primers in the sequence view.

<img width="816" alt="Image" src="https://github.com/user-attachments/assets/831ebd0f-994a-4fa5-97fd-8b5672f619a1" />


## Primer design

> Settings for next test (new flanking constraints)
> * Left flank reverse – within 20bp upstream of the gene/neutral site to 50bp into the gene.
> * Left flank forward – roughly 950bp upstream of the reverse primer (set the flank region as 900bp upstream of the gene/neutral site junction)
> * Right flank forward – within the last 50bp of gene/neutral site to 20bp downstream of the junction
> * Right flank reverse – roughly 950bp downstream of the forward primer

I think what you want can be achieved with the option `SEQUENCE_PRIMER_PAIR_OK_REGION_LIST` in the primer3 settings, see the image below. I think what I am doing is correct, but if you can please double-check so that we can be sure. I attach a figure with the logic + explanation

![Image](https://github.com/user-attachments/assets/6efa9b2b-d75c-4722-84f8-0acd7f682618)

1. **Overall Structure**

* The top of the diagram shows a region of interest (ROI) with padding (1000bp requested from NCBI on each side).
* The ROI is the central hatched area, with padding regions shown as boxes on either side
* Key Parameters
  * padding = 1000: The extra sequence taken on each side of the ROI
  * max_inside = 20: Maximum allowed primer overlap into the ROI
  * max_outside = 70: Maximum allowed primer position into the padding region

2. **Primer Design**

* The sequence is split into two subsequences to be fed into primer3, each of length `padding + max_inside`.
* On the left one, the forward primer can be placed anywhere in the range `[0, padding/2]`., whereas the reverse primer must be within the last `max_inside + max_outside` bases. The desired PCR product length can be specified in primer3 separately, now I have [800,1000] but it could be changed.
* The same logic applies to the right subsequence, but with the constraints reversed.

3. **Primer3 Settings**

To achieve this in primer3, I use the `SEQUENCE_PRIMER_PAIR_OK_REGION_LIST` option, which allows me to specify the allowed regions for the forward and reverse primers. This setting is documented [here](https://primer3.org/manual.html#SEQUENCE_PRIMER_PAIR_OK_REGION_LIST).

> The associated value must be a semicolon-separated list of
>
> ```
> <left_start>,<left_length>,<right_start>,<right_length>
> ```
>
> The left primer must be in the region specified by `<left_start>,<left_length>` and the right primer must be in the region specified by `<right_start>,<right_length>`. `<left_start>` and `<left_length>` specify the location of the left primer in terms of the index of the first base in the region and the length of the region. `<right_start>` and `<right_length>` specify the location of the right primer in analogous fashion.

The image shows the formula for the settings, which for the default values of `max_inside = 20` and `padding = 1000` gives:

* `0,500,930,90` for the left arm
* `0,90,520,500` for the right arm

**Comment by manulera** [comment]
Hi @AmandaHopes,

I have made a template for this, you can access it in the link below. For now you can only set the "Max inside" and "Max outside" parameters, but we can add all the others eventually.

https://opencloning.org/?source=example&example=ebic_template.json

To see how to use it, see the video below (with sound)

https://github.com/user-attachments/assets/11ff5599-cec5-42e8-b034-e9b2f5a4b876
